[package]
name = "notion_backup"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "4.0.0"
regex = "1.7.0"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"